### ISSUE TITLE
Posto Pluviométrico com posto de jusante inexistente.

### ISSUE THREAD

**Issue by carneirogoulart** [ONSBR/smapOnsR#30]
Boa tarde!

No arquivo configuracao.csv, o posto 65000 (RVerde) está com o posto 65 cadastrado como posto_jusante.
Porém, não existe a linha referente ao posto 65 no arquivo, retornando erro na totalização de previsões.

**Comment by felipe-treistman** [comment]
Bom dia! Obrigado por relatar esse problema.

O ajuste do arquivo de configuração foi feito no último commit
